#!/bin/sh
#
# $Id: xfig-wrapper,v 1.1 2015/08/18 12:07:04 roland Exp $
#
##########################################################################
#
# xfig-wrapper is a little shell script, which tries to work around the
# missing UTF-8 capabilities of xfig.
# For this it allows to use the content of environment variable XFIG_LC_CTYPE
# as LC_CTYPE.  If this is not set, it checks whether you use a UTF-8 locale.
# If this is the case, it tries to strip UTF-8 from the locale and checks,
# whether the result is defined.
#
##########################################################################
#
#   Copyright (C) 2015  Roland Rosenfeld <roland@spinnaker.de>
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License as
#   published by the Free Software Foundation; either version 2 of
#   the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
##########################################################################

if [ "x$XFIG_LC_CTYPE" != "x" ]
then
    # user defined XFIG_LC_CTYPE
    LC_CTYPE=$XFIG_LC_CTYPE
    export LC_CTYPE
else
    if [ $(locale charmap) = "UTF-8" ]
    then
	CTYPE=$(locale | grep ^LC_CTYPE)
	CTYPE=${CTYPE#LC_CTYPE=}
	CTYPE=${CTYPE#\"}
	CTYPE=${CTYPE%\"}
	CTYPE=${CTYPE%.[uU][tT][fF]*8} # strip utf8
	if locale -a | grep -q "^$CTYPE\$"
	then
	    LC_CTYPE=$CTYPE
	    export LC_CTYPE
	else
	    echo "no non-UTF-8 locale found, try setting XFIG_LC_CTYPE, if you have trouble with your charset"
	fi
    fi
fi	

xfig.real "$@"
